name: linters
on:
  workflow_call:
    inputs:
      ENABLE_LINTERS: #Input to decide which linter needs to be run
        description: "Comma Separated List of Linters.If ENABLE_LINTERS is set, only listed linters will be processed."
        required: false
        type: string
        default: "None"
jobs:
  linters:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    name: linters
    steps:
      - uses: ./actions/linters
        with:
          ENABLE_LINTERS: ${{ inputs.ENABLE_LINTERS }}
        id: linters